SOLVER:
  gpu: 0,
  logdir: ../../../implicit_ocnn/ae_mesh/
  ckpt: logs/ae/aocnn5_slim2_070/model/iter_050000.ckpt
  run: decode_shape
  max_iter: 320000
  test_iter: 100

DATA:
  test: 
    dtype: octree
    depth: 5
    location: dataset/m40_scanoctree.5.adaptive_test.tfrecords
    shuffle: 0
    batch_size: 1
    x_alias: data # be careful with this parameter

MODEL:
  name: ocnn
  channel: 12
  nout: 128   # the hidden code
  depth: 5

LOSS:
  num_class: 40
  weight_decay: 0.0005