SOLVER:
  gpu: 0,
  logdir: ../../../implicit_ocnn/ae_mesh/
  ckpt: logs/ae/aocnn3_slim2/model/iter_320000.ckpt
  run: decode_shape
  max_iter: 320000
  test_iter: 100

DATA:
  test: 
    dtype: octree
    depth: 3
    location: dataset/m40_3_2_12_test_octree.tfrecords
    shuffle: 1
    batch_size: 1
    x_alias: data # be careful with this parameter

MODEL:
  name: ocnn
  channel: 10
  nout: 128   # the hidden code
  depth: 3

LOSS:
  num_class: 40
  weight_decay: 0.0005