SOLVER:
  gpu: 0,
  logdir: logs/ae/aocnn3_slim2
  run: train
  max_iter: 320000
  test_iter: 248
  test_every_iter: 2000
  step_size: (80000,)

DATA:
  train:
    dtype: octree
    depth: 3
    location: dataset/m40_3_2_12_train_octree.tfrecords 
    batch_size: 16
    x_alias: data # be careful with this parameter
  test: 
    dtype: octree
    depth: 3
    location: dataset/m40_3_2_12_test_octree.tfrecords 
    shuffle: 0
    batch_size: 16
    x_alias: data # be careful with this parameter

MODEL:
  name: ocnn
  channel: 10
  nout: 128   # the hidden code
  depth: 3

LOSS:
  num_class: 40
  weight_decay: 0.0005