SOLVER:
  gpu: 0,
  logdir: /home/jeri/dev/data/ModelNet40/3_exp_baseline_planar_d5/
  run: train
  max_iter: 160000
  test_iter: 925
  test_every_iter: 2000
  step_size: (40000,)

DATA:
  train:
    dtype: octree
    distort: True
    depth: 5
    location: /home/jeri/dev/data/ModelNet40/3_exp_baseline_planar_d5/oct_train_aug.tfrecords
    batch_size: 32
    node_dis: True
    split_label: True
    x_alias: data
  test: 
    dtype: octree
    distort: False
    depth: 5
    location: /home/jeri/dev/data/ModelNet40/3_exp_baseline_planar_d5/oct_test.tfrecords
    shuffle: 0
    batch_size: 32
    node_dis: True
    split_label: True
    x_alias: data

MODEL:
  name: ocnn
  channel: 4
  nout: 40
  depth: 5

LOSS:
  num_class: 40
  weight_decay: 0.0005
